export const orderForm = {
  orderFormId: '03db3a179c7d4a9085152068b555eee1',
  salesChannel: '1',
  loggedIn: false,
  isCheckedIn: false,
  storeId: null,
  checkedInPickupPointId: null,
  allowManualPrice: false,
  canEditData: false,
  userProfileId: '4a69b43c-7bed-4bff-8251-aeabf69e6a44',
  userType: null,
  ignoreProfileData: false,
  value: 190044,
  messages: [
    {
      code: null,
      text: 'O tipo de entrega foi alterado',
      status: 'warning',
      fields: {},
    },
  ],
  items: [
    {
      uniqueId: '69552D2AC93041BEB5DE9D131BD2E4E2',
      id: '33',
      productId: '18',
      productRefId: '',
      refId: null,
      ean: '123456789154',
      name: 'Luxury Purple Ballon Luxury Purple Client Ballon',
      skuName: 'Luxury Purple Client Ballon',
      modalType: null,
      parentItemIndex: null,
      parentAssemblyBinding: null,
      assemblies: [],
      priceValidUntil: '2022-07-19T16:33:19Z',
      tax: 0,
      price: 1000,
      listPrice: 1000,
      manualPrice: null,
      manualPriceAppliedBy: null,
      sellingPrice: 1000,
      rewardValue: 0,
      isGift: false,
      additionalInfo: {
        dimension: null,
        brandName: 'Marca 3',
        brandId: '2000002',
        offeringInfo: null,
        offeringType: null,
        offeringTypeId: null,
      },
      preSaleDate: null,
      productCategoryIds: '/1/2/7/',
      productCategories: {
        '1': 'Departamento 1',
        '2': 'Categoria 2',
        '7': 'Sub-Categoria 7',
      },
      quantity: 2,
      seller: '1',
      sellerChain: ['1'],
      imageUrl:
        'http://pedrocruz.vteximg.com.br/arquivos/ids/155457-55-55/dog.jpg?v=637483293155100000',
      detailUrl: '/luxury-purple-ballon/p',
      components: [],
      bundleItems: [],
      attachments: [],
      attachmentOfferings: [],
      offerings: [],
      priceTags: [],
      availability: 'available',
      measurementUnit: 'un',
      unitMultiplier: 1,
      manufacturerCode: null,
      priceDefinition: {
        calculatedSellingPrice: 1000,
        total: 2000,
        sellingPrices: [
          {
            value: 1000,
            quantity: 2,
          },
        ],
      },
    },
    {
      uniqueId: '69552D2AC93041BEB5DE9D131BD2E4E2',
      id: '33',
      productId: '18',
      productRefId: '',
      refId: null,
      ean: '123456789154',
      name: 'Luxury Purple Ballon Luxury Purple Client Ballon',
      skuName: 'Luxury Purple Client Ballon',
      modalType: null,
      parentItemIndex: null,
      parentAssemblyBinding: null,
      assemblies: [],
      priceValidUntil: '2022-07-19T16:33:19Z',
      tax: 0,
      price: 1000,
      listPrice: 1000,
      manualPrice: null,
      manualPriceAppliedBy: null,
      sellingPrice: 300,
      rewardValue: 0,
      isGift: false,
      additionalInfo: {
        dimension: null,
        brandName: 'Marca 3',
        brandId: '2000002',
        offeringInfo: null,
        offeringType: null,
        offeringTypeId: null,
      },
      preSaleDate: null,
      productCategoryIds: '/1/2/7/',
      productCategories: {
        '1': 'Departamento 1',
        '2': 'Categoria 2',
        '7': 'Sub-Categoria 7',
      },
      quantity: 1,
      seller: '1',
      sellerChain: ['1'],
      imageUrl:
        'http://pedrocruz.vteximg.com.br/arquivos/ids/155457-55-55/dog.jpg?v=637483293155100000',
      detailUrl: '/luxury-purple-ballon/p',
      components: [],
      bundleItems: [],
      attachments: [],
      attachmentOfferings: [],
      offerings: [],
      priceTags: [
        {
          name:
            'discount@price-3f0c2115-10a6-4fda-aec4-5950d8de9a6c#52351d37-737a-4ab4-9725-a98f1847a6be',
          value: -700,
          rawValue: -7,
          isPercentual: false,
          identifier: '3f0c2115-10a6-4fda-aec4-5950d8de9a6c',
        },
      ],
      availability: 'available',
      measurementUnit: 'un',
      unitMultiplier: 1,
      manufacturerCode: null,
      priceDefinition: {
        calculatedSellingPrice: 300,
        total: 300,
        sellingPrices: [
          {
            value: 300,
            quantity: 1,
          },
        ],
      },
    },
    {
      uniqueId: '9DED33A8C9C44FE8BD50302C819C470C',
      id: '5',
      productId: '3',
      productRefId: '',
      refId: null,
      ean: '123456789127',
      name: 'Produto 3 SKU 5',
      skuName: 'SKU 5',
      modalType: null,
      parentItemIndex: null,
      parentAssemblyBinding: null,
      assemblies: [],
      priceValidUntil: '2022-07-19T16:33:19Z',
      tax: 0,
      price: 135714,
      listPrice: 135714,
      manualPrice: null,
      manualPriceAppliedBy: null,
      sellingPrice: 135714,
      rewardValue: 0,
      isGift: false,
      additionalInfo: {
        dimension: null,
        brandName: 'Marca 3',
        brandId: '2000002',
        offeringInfo: null,
        offeringType: null,
        offeringTypeId: null,
      },
      preSaleDate: null,
      productCategoryIds: '/1/2/7/',
      productCategories: {
        '1': 'Departamento 1',
        '2': 'Categoria 2',
        '7': 'Sub-Categoria 7',
      },
      quantity: 1,
      seller: '1',
      sellerChain: ['1'],
      imageUrl:
        'http://pedrocruz.vteximg.com.br/arquivos/ids/155405-55-55/numero-51.jpg?v=637457563330030000',
      detailUrl: '/produto-3/p',
      components: [],
      bundleItems: [],
      attachments: [],
      attachmentOfferings: [],
      offerings: [],
      priceTags: [],
      availability: 'available',
      measurementUnit: 'un',
      unitMultiplier: 1,
      manufacturerCode: null,
      priceDefinition: {
        calculatedSellingPrice: 135714,
        total: 135714,
        sellingPrices: [
          {
            value: 135714,
            quantity: 1,
          },
        ],
      },
    },
    {
      uniqueId: '19C53CFEDCC2473BA1A983B983AE456E',
      id: '30',
      productId: '15',
      productRefId: '',
      refId: null,
      ean: '123456789152',
      name: 'Produto 15 (Assinatura) SKU 30 (Assinatura)',
      skuName: 'SKU 30 (Assinatura)',
      modalType: null,
      parentItemIndex: null,
      parentAssemblyBinding: null,
      assemblies: [],
      priceValidUntil: '2022-07-19T16:33:19Z',
      tax: 0,
      price: 2000,
      listPrice: 2000,
      manualPrice: null,
      manualPriceAppliedBy: null,
      sellingPrice: 2000,
      rewardValue: 0,
      isGift: false,
      additionalInfo: {
        dimension: null,
        brandName: 'Marca 3',
        brandId: '2000002',
        offeringInfo: null,
        offeringType: null,
        offeringTypeId: null,
      },
      preSaleDate: null,
      productCategoryIds: '/1/2/7/',
      productCategories: {
        '1': 'Departamento 1',
        '2': 'Categoria 2',
        '7': 'Sub-Categoria 7',
      },
      quantity: 1,
      seller: '1',
      sellerChain: ['1'],
      imageUrl:
        'http://pedrocruz.vteximg.com.br/arquivos/ids/155454-55-55/5800711534cfbfb6ca9649db2c02c603.jpg?v=637478033140470000',
      detailUrl: '/produto-15-assinatura/p',
      components: [],
      bundleItems: [],
      attachments: [
        {
          name: 'vtex.subscription.assinatura',
          content: {
            'vtex.subscription.key.frequency': '1 day',
          },
        },
      ],
      attachmentOfferings: [
        {
          name: 'vtex.subscription.assinatura',
          required: false,
          schema: {
            'vtex.subscription.key.frequency': {
              maximumNumberOfCharacters: 5,
              domain: ['1 day'],
            },
          },
        },
      ],
      offerings: [],
      priceTags: [],
      availability: 'available',
      measurementUnit: 'un',
      unitMultiplier: 1,
      manufacturerCode: null,
      priceDefinition: {
        calculatedSellingPrice: 2000,
        total: 2000,
        sellingPrices: [
          {
            value: 2000,
            quantity: 1,
          },
        ],
      },
    },
    {
      uniqueId: 'B9E6F3861C914C95BE6421E88B48C45A',
      id: '30',
      productId: '15',
      productRefId: '',
      refId: null,
      ean: '123456789152',
      name: 'Produto 15 (Assinatura) SKU 30 (Assinatura)',
      skuName: 'SKU 30 (Assinatura)',
      modalType: null,
      parentItemIndex: null,
      parentAssemblyBinding: null,
      assemblies: [],
      priceValidUntil: '2022-07-19T16:33:19Z',
      tax: 0,
      price: 2000,
      listPrice: 2000,
      manualPrice: null,
      manualPriceAppliedBy: null,
      sellingPrice: 2000,
      rewardValue: 0,
      isGift: false,
      additionalInfo: {
        dimension: null,
        brandName: 'Marca 3',
        brandId: '2000002',
        offeringInfo: null,
        offeringType: null,
        offeringTypeId: null,
      },
      preSaleDate: null,
      productCategoryIds: '/1/2/7/',
      productCategories: {
        '1': 'Departamento 1',
        '2': 'Categoria 2',
        '7': 'Sub-Categoria 7',
      },
      quantity: 2,
      seller: '1',
      sellerChain: ['1'],
      imageUrl:
        'http://pedrocruz.vteximg.com.br/arquivos/ids/155454-55-55/5800711534cfbfb6ca9649db2c02c603.jpg?v=637478033140470000',
      detailUrl: '/produto-15-assinatura/p',
      components: [],
      bundleItems: [],
      attachments: [
        {
          name: 'vtex.subscription.assinatura',
          content: {
            'vtex.subscription.key.frequency': '1 day',
          },
        },
      ],
      attachmentOfferings: [
        {
          name: 'vtex.subscription.assinatura',
          required: false,
          schema: {
            'vtex.subscription.key.frequency': {
              maximumNumberOfCharacters: 5,
              domain: ['1 day'],
            },
          },
        },
      ],
      offerings: [],
      priceTags: [],
      availability: 'available',
      measurementUnit: 'un',
      unitMultiplier: 1,
      manufacturerCode: null,
      priceDefinition: {
        calculatedSellingPrice: 2000,
        total: 4000,
        sellingPrices: [
          {
            value: 2000,
            quantity: 2,
          },
        ],
      },
    },
    {
      uniqueId: '6EBBBDEBFAB34685B8CE7042722899D6',
      id: '30',
      productId: '15',
      productRefId: '',
      refId: null,
      ean: '123456789152',
      name: 'Produto 15 (Assinatura) SKU 30 (Assinatura)',
      skuName: 'SKU 30 (Assinatura)',
      modalType: null,
      parentItemIndex: null,
      parentAssemblyBinding: null,
      assemblies: [],
      priceValidUntil: '2022-07-19T16:33:19Z',
      tax: 0,
      price: 2000,
      listPrice: 2000,
      manualPrice: null,
      manualPriceAppliedBy: null,
      sellingPrice: 2000,
      rewardValue: 0,
      isGift: false,
      additionalInfo: {
        dimension: null,
        brandName: 'Marca 3',
        brandId: '2000002',
        offeringInfo: null,
        offeringType: null,
        offeringTypeId: null,
      },
      preSaleDate: null,
      productCategoryIds: '/1/2/7/',
      productCategories: {
        '1': 'Departamento 1',
        '2': 'Categoria 2',
        '7': 'Sub-Categoria 7',
      },
      quantity: 1,
      seller: '1',
      sellerChain: ['1'],
      imageUrl:
        'http://pedrocruz.vteximg.com.br/arquivos/ids/155454-55-55/5800711534cfbfb6ca9649db2c02c603.jpg?v=637478033140470000',
      detailUrl: '/produto-15-assinatura/p',
      components: [],
      bundleItems: [],
      attachments: [],
      attachmentOfferings: [
        {
          name: 'vtex.subscription.assinatura',
          required: false,
          schema: {
            'vtex.subscription.key.frequency': {
              maximumNumberOfCharacters: 5,
              domain: ['1 day'],
            },
          },
        },
      ],
      offerings: [],
      priceTags: [],
      availability: 'available',
      measurementUnit: 'un',
      unitMultiplier: 1,
      manufacturerCode: null,
      priceDefinition: {
        calculatedSellingPrice: 2000,
        total: 2000,
        sellingPrices: [
          {
            value: 2000,
            quantity: 1,
          },
        ],
      },
    },
  ],
  selectableGifts: [],
  totalizers: [
    {
      id: 'Items',
      name: 'Total dos Itens',
      value: 146714,
    },
    {
      id: 'Discounts',
      name: 'Total dos Descontos',
      value: -700,
    },
    {
      id: 'Shipping',
      name: 'Total do Frete',
      value: 44030,
    },
  ],
  shippingData: {
    address: {
      addressType: 'residential',
      receiverName: 'PEd** ****',
      addressId: '4830634440150',
      isDisposable: false,
      postalCode: '******000',
      city: 'e',
      state: 'MS',
      country: 'BRA',
      street: 'e',
      number: '*',
      neighborhood: 'e',
      complement: '*',
      reference: null,
      geoCoordinates: [],
    },
    logisticsInfo: [
      {
        itemIndex: 0,
        selectedSla: 'ME Transportadora Genérica',
        selectedDeliveryChannel: 'delivery',
        addressId: '4830634440150',
        slas: [
          {
            id: 'ME Transportadora Genérica',
            deliveryChannel: 'delivery',
            name: 'ME Transportadora Genérica',
            deliveryIds: [
              {
                courierId: 'IDTransportadoraGenerica',
                warehouseId: 'IDEstoqueGenerico',
                dockId: 'IDDocaGenerica',
                courierName: 'Transportadora Genérica',
                quantity: 2,
                kitItemDetails: [],
              },
            ],
            shippingEstimate: '8bd',
            shippingEstimateDate: null,
            lockTTL: null,
            availableDeliveryWindows: [],
            deliveryWindow: null,
            price: 1348,
            listPrice: 1348,
            tax: 0,
            pickupStoreInfo: {
              isPickupStore: false,
              friendlyName: null,
              address: null,
              additionalInfo: null,
              dockId: null,
            },
            pickupPointId: null,
            pickupDistance: 0,
            polygonName: null,
            transitTime: '0bd',
          },
        ],
        shipsTo: ['BRA'],
        itemId: '33',
        deliveryChannels: [
          {
            id: 'delivery',
          },
        ],
      },
      {
        itemIndex: 1,
        selectedSla: 'ME Transportadora Genérica',
        selectedDeliveryChannel: 'delivery',
        addressId: '4830634440150',
        slas: [
          {
            id: 'ME Transportadora Genérica',
            deliveryChannel: 'delivery',
            name: 'ME Transportadora Genérica',
            deliveryIds: [
              {
                courierId: 'IDTransportadoraGenerica',
                warehouseId: 'IDEstoqueGenerico',
                dockId: 'IDDocaGenerica',
                courierName: 'Transportadora Genérica',
                quantity: 1,
                kitItemDetails: [],
              },
            ],
            shippingEstimate: '8bd',
            shippingEstimateDate: null,
            lockTTL: null,
            availableDeliveryWindows: [],
            deliveryWindow: null,
            price: 673,
            listPrice: 673,
            tax: 0,
            pickupStoreInfo: {
              isPickupStore: false,
              friendlyName: null,
              address: null,
              additionalInfo: null,
              dockId: null,
            },
            pickupPointId: null,
            pickupDistance: 0,
            polygonName: null,
            transitTime: '0bd',
          },
        ],
        shipsTo: ['BRA'],
        itemId: '33',
        deliveryChannels: [
          {
            id: 'delivery',
          },
        ],
      },
      {
        itemIndex: 2,
        selectedSla: 'ME Transportadora Produto 3',
        selectedDeliveryChannel: 'delivery',
        addressId: '4830634440150',
        slas: [
          {
            id: 'ME Transportadora Produto 3',
            deliveryChannel: 'delivery',
            name: 'ME Transportadora Produto 3',
            deliveryIds: [
              {
                courierId: 'IDTransportadoraProduto3',
                warehouseId: 'IDEstoqueProduto3',
                dockId: 'IDDocaProduto3',
                courierName: 'Transportadora Produto 3',
                quantity: 1,
                kitItemDetails: [],
              },
            ],
            shippingEstimate: '1bd',
            shippingEstimateDate: null,
            lockTTL: null,
            availableDeliveryWindows: [],
            deliveryWindow: null,
            price: 39314,
            listPrice: 39314,
            tax: 0,
            pickupStoreInfo: {
              isPickupStore: false,
              friendlyName: null,
              address: null,
              additionalInfo: null,
              dockId: null,
            },
            pickupPointId: null,
            pickupDistance: 0,
            polygonName: null,
            transitTime: '0bd',
          },
          {
            id: 'ME Transportadora Produto 1',
            deliveryChannel: 'delivery',
            name: 'ME Transportadora Produto 1',
            deliveryIds: [
              {
                courierId: 'IDTransportadoraProduto1',
                warehouseId: 'IDEstoqueProduto3',
                dockId: 'IDDocaProduto123',
                courierName: 'Transportadora Produto 1',
                quantity: 1,
                kitItemDetails: [],
              },
            ],
            shippingEstimate: '3bd',
            shippingEstimateDate: null,
            lockTTL: null,
            availableDeliveryWindows: [],
            deliveryWindow: null,
            price: 39314,
            listPrice: 39314,
            tax: 0,
            pickupStoreInfo: {
              isPickupStore: false,
              friendlyName: null,
              address: null,
              additionalInfo: null,
              dockId: null,
            },
            pickupPointId: null,
            pickupDistance: 0,
            polygonName: null,
            transitTime: '0bd',
          },
          {
            id: 'ME Transportadora Produto 2',
            deliveryChannel: 'delivery',
            name: 'ME Transportadora Produto 2',
            deliveryIds: [
              {
                courierId: 'IDTransportadoraProduto2',
                warehouseId: 'IDEstoqueProduto3',
                dockId: 'IDDocaProduto123',
                courierName: 'Transportadora Produto 2',
                quantity: 1,
                kitItemDetails: [],
              },
            ],
            shippingEstimate: '3bd',
            shippingEstimateDate: null,
            lockTTL: null,
            availableDeliveryWindows: [],
            deliveryWindow: null,
            price: 39314,
            listPrice: 39314,
            tax: 0,
            pickupStoreInfo: {
              isPickupStore: false,
              friendlyName: null,
              address: null,
              additionalInfo: null,
              dockId: null,
            },
            pickupPointId: null,
            pickupDistance: 0,
            polygonName: null,
            transitTime: '0bd',
          },
        ],
        shipsTo: ['BRA'],
        itemId: '5',
        deliveryChannels: [
          {
            id: 'delivery',
          },
        ],
      },
      {
        itemIndex: 3,
        selectedSla: 'ME Transportadora Genérica',
        selectedDeliveryChannel: 'delivery',
        addressId: '4830634440150',
        slas: [
          {
            id: 'ME Transportadora Genérica',
            deliveryChannel: 'delivery',
            name: 'ME Transportadora Genérica',
            deliveryIds: [
              {
                courierId: 'IDTransportadoraGenerica',
                warehouseId: 'IDEstoqueGenerico',
                dockId: 'IDDocaGenerica',
                courierName: 'Transportadora Genérica',
                quantity: 1,
                kitItemDetails: [],
              },
            ],
            shippingEstimate: '8bd',
            shippingEstimateDate: null,
            lockTTL: null,
            availableDeliveryWindows: [],
            deliveryWindow: null,
            price: 674,
            listPrice: 674,
            tax: 0,
            pickupStoreInfo: {
              isPickupStore: false,
              friendlyName: null,
              address: null,
              additionalInfo: null,
              dockId: null,
            },
            pickupPointId: null,
            pickupDistance: 0,
            polygonName: null,
            transitTime: '0bd',
          },
        ],
        shipsTo: ['BRA'],
        itemId: '30',
        deliveryChannels: [
          {
            id: 'delivery',
          },
        ],
      },
      {
        itemIndex: 4,
        selectedSla: 'ME Transportadora Genérica',
        selectedDeliveryChannel: 'delivery',
        addressId: '4830634440150',
        slas: [
          {
            id: 'ME Transportadora Genérica',
            deliveryChannel: 'delivery',
            name: 'ME Transportadora Genérica',
            deliveryIds: [
              {
                courierId: 'IDTransportadoraGenerica',
                warehouseId: 'IDEstoqueGenerico',
                dockId: 'IDDocaGenerica',
                courierName: 'Transportadora Genérica',
                quantity: 2,
                kitItemDetails: [],
              },
            ],
            shippingEstimate: '8bd',
            shippingEstimateDate: null,
            lockTTL: null,
            availableDeliveryWindows: [],
            deliveryWindow: null,
            price: 1348,
            listPrice: 1348,
            tax: 0,
            pickupStoreInfo: {
              isPickupStore: false,
              friendlyName: null,
              address: null,
              additionalInfo: null,
              dockId: null,
            },
            pickupPointId: null,
            pickupDistance: 0,
            polygonName: null,
            transitTime: '0bd',
          },
        ],
        shipsTo: ['BRA'],
        itemId: '30',
        deliveryChannels: [
          {
            id: 'delivery',
          },
        ],
      },
      {
        itemIndex: 5,
        selectedSla: 'ME Transportadora Genérica',
        selectedDeliveryChannel: 'delivery',
        addressId: '4830634440150',
        slas: [
          {
            id: 'ME Transportadora Genérica',
            deliveryChannel: 'delivery',
            name: 'ME Transportadora Genérica',
            deliveryIds: [
              {
                courierId: 'IDTransportadoraGenerica',
                warehouseId: 'IDEstoqueGenerico',
                dockId: 'IDDocaGenerica',
                courierName: 'Transportadora Genérica',
                quantity: 1,
                kitItemDetails: [],
              },
            ],
            shippingEstimate: '8bd',
            shippingEstimateDate: null,
            lockTTL: null,
            availableDeliveryWindows: [],
            deliveryWindow: null,
            price: 673,
            listPrice: 673,
            tax: 0,
            pickupStoreInfo: {
              isPickupStore: false,
              friendlyName: null,
              address: null,
              additionalInfo: null,
              dockId: null,
            },
            pickupPointId: null,
            pickupDistance: 0,
            polygonName: null,
            transitTime: '0bd',
          },
        ],
        shipsTo: ['BRA'],
        itemId: '30',
        deliveryChannels: [
          {
            id: 'delivery',
          },
        ],
      },
    ],
    selectedAddresses: [
      {
        addressType: 'residential',
        receiverName: 'PEd** ****',
        addressId: '4830634440150',
        isDisposable: false,
        postalCode: '******000',
        city: 'e',
        state: 'MS',
        country: 'BRA',
        street: 'e',
        number: '*',
        neighborhood: 'e',
        complement: '*',
        reference: null,
        geoCoordinates: [],
      },
    ],
    availableAddresses: [
      {
        addressType: 'residential',
        receiverName: 'PEd** ****',
        addressId: '4847485716870',
        isDisposable: false,
        postalCode: '******000',
        city: 'wed**',
        state: 'MG',
        country: 'BRA',
        street: '*ua',
        number: '***',
        neighborhood: '234*',
        complement: null,
        reference: null,
        geoCoordinates: [],
      },
      {
        addressType: 'residential',
        receiverName: 'PEd** ****',
        addressId: '4830634440150',
        isDisposable: false,
        postalCode: '******000',
        city: 'e',
        state: 'MS',
        country: 'BRA',
        street: 'e',
        number: '*',
        neighborhood: 'e',
        complement: '*',
        reference: null,
        geoCoordinates: [],
      },
    ],
    pickupPoints: [],
  },
  clientProfileData: {
    email: 'pedrovtex1@gmail.com',
    firstName: 'PEd**',
    lastName: 'Cru*',
    document: '*9*2*9*6*8*',
    documentType: 'cpf',
    phone: '**********9999',
    corporateName: null,
    tradeName: null,
    corporateDocument: null,
    stateInscription: null,
    corporatePhone: null,
    isCorporate: false,
    profileCompleteOnLoading: true,
    profileErrorOnLoading: false,
    customerClass: null,
  },
  paymentData: {
    updateStatus: 'updated',
    installmentOptions: [
      {
        paymentSystem: '2',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 190044,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 190044,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 190044,
                total: 190044,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 95022,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 95022,
                total: 190044,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 63348,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 63348,
                total: 190044,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 47511,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 47511,
                total: 190044,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 38008,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 38008,
                total: 190044,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 31674,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 31674,
                total: 190044,
              },
            ],
          },
          {
            count: 7,
            hasInterestRate: false,
            interestRate: 0,
            value: 27149,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 7,
                hasInterestRate: false,
                interestRate: 0,
                value: 27149,
                total: 190044,
              },
            ],
          },
          {
            count: 8,
            hasInterestRate: false,
            interestRate: 0,
            value: 23755,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 8,
                hasInterestRate: false,
                interestRate: 0,
                value: 23755,
                total: 190044,
              },
            ],
          },
          {
            count: 9,
            hasInterestRate: false,
            interestRate: 0,
            value: 21116,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 9,
                hasInterestRate: false,
                interestRate: 0,
                value: 21116,
                total: 190044,
              },
            ],
          },
          {
            count: 10,
            hasInterestRate: false,
            interestRate: 0,
            value: 19004,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 10,
                hasInterestRate: false,
                interestRate: 0,
                value: 19004,
                total: 190044,
              },
            ],
          },
          {
            count: 11,
            hasInterestRate: false,
            interestRate: 0,
            value: 17276,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 11,
                hasInterestRate: false,
                interestRate: 0,
                value: 17276,
                total: 190044,
              },
            ],
          },
          {
            count: 12,
            hasInterestRate: false,
            interestRate: 0,
            value: 15837,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 12,
                hasInterestRate: false,
                interestRate: 0,
                value: 15837,
                total: 190044,
              },
            ],
          },
          {
            count: 13,
            hasInterestRate: false,
            interestRate: 0,
            value: 14618,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 13,
                hasInterestRate: false,
                interestRate: 0,
                value: 14618,
                total: 190044,
              },
            ],
          },
          {
            count: 14,
            hasInterestRate: false,
            interestRate: 0,
            value: 13574,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 14,
                hasInterestRate: false,
                interestRate: 0,
                value: 13574,
                total: 190044,
              },
            ],
          },
          {
            count: 15,
            hasInterestRate: false,
            interestRate: 0,
            value: 12669,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 15,
                hasInterestRate: false,
                interestRate: 0,
                value: 12669,
                total: 190044,
              },
            ],
          },
          {
            count: 16,
            hasInterestRate: false,
            interestRate: 0,
            value: 11877,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 16,
                hasInterestRate: false,
                interestRate: 0,
                value: 11877,
                total: 190044,
              },
            ],
          },
          {
            count: 17,
            hasInterestRate: false,
            interestRate: 0,
            value: 11179,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 17,
                hasInterestRate: false,
                interestRate: 0,
                value: 11179,
                total: 190044,
              },
            ],
          },
          {
            count: 18,
            hasInterestRate: false,
            interestRate: 0,
            value: 10558,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 18,
                hasInterestRate: false,
                interestRate: 0,
                value: 10558,
                total: 190044,
              },
            ],
          },
          {
            count: 19,
            hasInterestRate: false,
            interestRate: 0,
            value: 10002,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 19,
                hasInterestRate: false,
                interestRate: 0,
                value: 10002,
                total: 190044,
              },
            ],
          },
          {
            count: 20,
            hasInterestRate: false,
            interestRate: 0,
            value: 9502,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 20,
                hasInterestRate: false,
                interestRate: 0,
                value: 9502,
                total: 190044,
              },
            ],
          },
          {
            count: 21,
            hasInterestRate: false,
            interestRate: 0,
            value: 9049,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 21,
                hasInterestRate: false,
                interestRate: 0,
                value: 9049,
                total: 190044,
              },
            ],
          },
          {
            count: 22,
            hasInterestRate: false,
            interestRate: 0,
            value: 8638,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 22,
                hasInterestRate: false,
                interestRate: 0,
                value: 8638,
                total: 190044,
              },
            ],
          },
          {
            count: 23,
            hasInterestRate: false,
            interestRate: 0,
            value: 8262,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 23,
                hasInterestRate: false,
                interestRate: 0,
                value: 8262,
                total: 190044,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '4',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 190044,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 190044,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 190044,
                total: 190044,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 95022,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 95022,
                total: 190044,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 63348,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 63348,
                total: 190044,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 47511,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 47511,
                total: 190044,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 38008,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 38008,
                total: 190044,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 31674,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 31674,
                total: 190044,
              },
            ],
          },
          {
            count: 7,
            hasInterestRate: false,
            interestRate: 0,
            value: 27149,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 7,
                hasInterestRate: false,
                interestRate: 0,
                value: 27149,
                total: 190044,
              },
            ],
          },
          {
            count: 8,
            hasInterestRate: false,
            interestRate: 0,
            value: 23755,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 8,
                hasInterestRate: false,
                interestRate: 0,
                value: 23755,
                total: 190044,
              },
            ],
          },
          {
            count: 9,
            hasInterestRate: false,
            interestRate: 0,
            value: 21116,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 9,
                hasInterestRate: false,
                interestRate: 0,
                value: 21116,
                total: 190044,
              },
            ],
          },
          {
            count: 10,
            hasInterestRate: false,
            interestRate: 0,
            value: 19004,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 10,
                hasInterestRate: false,
                interestRate: 0,
                value: 19004,
                total: 190044,
              },
            ],
          },
          {
            count: 11,
            hasInterestRate: false,
            interestRate: 0,
            value: 17276,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 11,
                hasInterestRate: false,
                interestRate: 0,
                value: 17276,
                total: 190044,
              },
            ],
          },
          {
            count: 12,
            hasInterestRate: false,
            interestRate: 0,
            value: 15837,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 12,
                hasInterestRate: false,
                interestRate: 0,
                value: 15837,
                total: 190044,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '4',
        bin: '544444',
        paymentName: null,
        paymentGroupName: null,
        value: 190044,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 190044,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 190044,
                total: 190044,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 95022,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 95022,
                total: 190044,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 63348,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 63348,
                total: 190044,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 47511,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 47511,
                total: 190044,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 38008,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 38008,
                total: 190044,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 31674,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 31674,
                total: 190044,
              },
            ],
          },
          {
            count: 7,
            hasInterestRate: false,
            interestRate: 0,
            value: 27149,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 7,
                hasInterestRate: false,
                interestRate: 0,
                value: 27149,
                total: 190044,
              },
            ],
          },
          {
            count: 8,
            hasInterestRate: false,
            interestRate: 0,
            value: 23755,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 8,
                hasInterestRate: false,
                interestRate: 0,
                value: 23755,
                total: 190044,
              },
            ],
          },
          {
            count: 9,
            hasInterestRate: false,
            interestRate: 0,
            value: 21116,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 9,
                hasInterestRate: false,
                interestRate: 0,
                value: 21116,
                total: 190044,
              },
            ],
          },
          {
            count: 10,
            hasInterestRate: false,
            interestRate: 0,
            value: 19004,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 10,
                hasInterestRate: false,
                interestRate: 0,
                value: 19004,
                total: 190044,
              },
            ],
          },
          {
            count: 11,
            hasInterestRate: false,
            interestRate: 0,
            value: 17276,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 11,
                hasInterestRate: false,
                interestRate: 0,
                value: 17276,
                total: 190044,
              },
            ],
          },
          {
            count: 12,
            hasInterestRate: false,
            interestRate: 0,
            value: 15837,
            total: 190044,
            sellerMerchantInstallments: [
              {
                id: 'PEDROCRUZ',
                count: 12,
                hasInterestRate: false,
                interestRate: 0,
                value: 15837,
                total: 190044,
              },
            ],
          },
        ],
      },
    ],
    paymentSystems: [
      {
        id: 4,
        name: 'Mastercard',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex:
            '^((5(([1-2]|[4-5])[0-9]{8}|0((1|6)([0-9]{7}))|3(0(4((0|[2-9])[0-9]{5})|([0-3]|[5-9])[0-9]{6})|[1-9][0-9]{7})))|((508116)\\d{4,10})|((502121)\\d{4,10})|((589916)\\d{4,10})|(2[0-9]{15})|(67[0-9]{14})|(506387)\\d{4,10})',
          mask: '9999 9999 9999 9999',
          cardCodeRegex: '^[0-9]{3}$',
          cardCodeMask: '999',
          weights: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '4',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: false,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2021-07-26T16:32:20.2085451Z',
        availablePayments: null,
      },
      {
        id: 2,
        name: 'Visa',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex: '^4[0-9]{15}$',
          mask: '9999 9999 9999 9999',
          cardCodeRegex: '^[0-9]{3}$',
          cardCodeMask: '999',
          weights: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '2',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: false,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2021-07-26T16:32:20.2085451Z',
        availablePayments: null,
      },
    ],
    payments: [
      {
        paymentSystem: '4',
        bin: '544444',
        accountId: 'F4AB2D372E3A4303BB9482BD826525EF',
        tokenId: null,
        installments: 2,
        referenceValue: 190044,
        value: 190044,
        merchantSellerPayments: [
          {
            id: 'PEDROCRUZ',
            installments: 2,
            referenceValue: 190044,
            value: 190044,
            interestRate: 0,
            installmentValue: 95022,
          },
        ],
      },
    ],
    giftCards: [],
    giftCardMessages: [],
    availableAccounts: [
      {
        accountId: 'F4AB2D372E3A4303BB9482BD826525EF',
        paymentSystem: '4',
        paymentSystemName: 'Mastercard',
        cardNumber: '************4444',
        bin: '544444',
        availableAddresses: ['4847485716870', '4830634440150'],
        isExpired: false,
      },
    ],
    availableTokens: [],
  },
  marketingData: null,
  sellers: [
    {
      id: '1',
      name: 'Jovem Pedro B2C',
      logo: '',
    },
  ],
  clientPreferencesData: {
    locale: 'pt-BR',
    optinNewsLetter: false,
  },
  commercialConditionData: null,
  storePreferencesData: {
    countryCode: 'BRA',
    saveUserData: true,
    timeZone: 'E. South America Standard Time',
    currencyCode: 'BRL',
    currencyLocale: 1046,
    currencySymbol: 'R$',
    currencyFormatInfo: {
      currencyDecimalDigits: 2,
      currencyDecimalSeparator: ',',
      currencyGroupSeparator: '.',
      currencyGroupSize: 3,
      startsWithCurrencySymbol: true,
    },
  },
  giftRegistryData: null,
  openTextField: null,
  invoiceData: null,
  customData: {
    customApps: [
      {
        fields: {
          quantity: '44',
        },
        id: 'customer-credit',
        major: 1,
      },
    ],
  },
  itemMetadata: {
    items: [
      {
        id: '33',
        seller: '1',
        name: 'Luxury Purple Ballon Luxury Purple Client Ballon',
        skuName: 'Luxury Purple Client Ballon',
        productId: '18',
        refId: null,
        ean: '123456789154',
        imageUrl:
          'http://pedrocruz.vteximg.com.br/arquivos/ids/155457-55-55/dog.jpg?v=637483293155100000',
        detailUrl: '/luxury-purple-ballon/p',
        assemblyOptions: [],
      },
      {
        id: '5',
        seller: '1',
        name: 'Produto 3 SKU 5',
        skuName: 'SKU 5',
        productId: '3',
        refId: null,
        ean: '123456789127',
        imageUrl:
          'http://pedrocruz.vteximg.com.br/arquivos/ids/155405-55-55/numero-51.jpg?v=637457563330030000',
        detailUrl: '/produto-3/p',
        assemblyOptions: [],
      },
      {
        id: '30',
        seller: '1',
        name: 'Produto 15 (Assinatura) SKU 30 (Assinatura)',
        skuName: 'SKU 30 (Assinatura)',
        productId: '15',
        refId: null,
        ean: '123456789152',
        imageUrl:
          'http://pedrocruz.vteximg.com.br/arquivos/ids/155454-55-55/5800711534cfbfb6ca9649db2c02c603.jpg?v=637478033140470000',
        detailUrl: '/produto-15-assinatura/p',
        assemblyOptions: [
          {
            id: 'vtex.subscription.assinatura',
            name: 'vtex.subscription.assinatura',
            required: false,
            inputValues: {
              'vtex.subscription.key.frequency': {
                maximumNumberOfCharacters: 5,
                domain: ['1 day'],
              },
            },
            composition: null,
          },
        ],
      },
    ],
  },
  hooksData: null,
  ratesAndBenefitsData: {
    rateAndBenefitsIdentifiers: [
      {
        id: '3f0c2115-10a6-4fda-aec4-5950d8de9a6c',
        name: 'Leve Mais',
        featured: false,
        description: null,
        matchedParameters: {
          'forThePriceOf@Marketing': '33',
          'usedItemsInPromotion@Marketing': '33',
        },
        additionalInfo: null,
      },
    ],
    teaser: [],
  },
  subscriptionData: {
    subscriptions: [
      {
        itemIndex: 3,
        plan: {
          validity: {
            begin: '2021-07-16T00:00:00',
            end: '2024-07-16T00:00:00',
          },
          frequency: {
            periodicity: 'DAY',
            interval: 1,
          },
          type: 'RECURRING_PAYMENT',
        },
        executionCount: 0,
      },
      {
        itemIndex: 4,
        plan: {
          validity: {
            begin: '2021-07-16T00:00:00',
            end: '2024-07-16T00:00:00',
          },
          frequency: {
            periodicity: 'DAY',
            interval: 1,
          },
          type: 'RECURRING_PAYMENT',
        },
        executionCount: 0,
      },
    ],
  },
  itemsOrdination: null,
}
